---
- name: create ANTs directories
  file:
    path: /opt/quarantine/ANTs/build
    state: directory

- name: clone ANTs
  git:
    repo: https://github.com/ANTsX/ANTs.git
    dest: /opt/quarantine/ANTs/src
    version: 28dd25cd9b9cb616d0ebf3adcb32ce74992c674a #2021-11-13

- name: configure and install ANTs
  shell: cmake -GNinja -DUSE_VTK=ON -DITK_BUILD_MINC_SUPPORT=ON -DBUILD_TESTING=OFF -DRUN_LONG_TESTS=OFF -DRUN_SHORT_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/opt/quarantine/ANTs -DSuperBuild_ANTS_USE_GIT_PROTOCOL=OFF ../src && cmake --build . && cd ANTS-build && cmake --install .
  args:
    chdir: /opt/quarantine/ANTs/build
    creates: /opt/quarantine/ANTs/bin

- name: add ANTs to path
  lineinfile:
    path: /etc/profile.d/99ANTs.sh
    line: "export PATH=/opt/quarantine/ANTs/bin${PATH:+:$PATH} && export ANTSPATH=/opt/quarantine/ANTs/bin"
    create: yes

- name: Install antspyx dependencies
  shell: /opt/quarantine/anaconda/bin/mamba install --yes -S chart-studio webcolors
  when:
    - '"python" in ansible_run_tags or "all" in ansible_run_tags'

- name: Install antspyx
  pip:
    name: antspyx
    executable: /opt/quarantine/anaconda/bin/pip
  when:
    - '"python" in ansible_run_tags or "all" in ansible_run_tags'
