#PyQC
#antsRegistration-MAGeT

- name: Install Common APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - default-jre

- name: Install bpipe
  unarchive:
    src: https://github.com/ssadedin/bpipe/releases/download/0.9.9.9/bpipe-0.9.9.9.tar.gz
    dest: /opt/quarantine
    creates: /opt/quarantine/bpipe-0.9.9.9
    remote_src: yes

- name: add bpipe to path
  lineinfile:
    path: /etc/profile.d/99bpipe.sh
    line: "export PATH=/opt/quarantine/bpipe-0.9.9.9/bin${PATH:+:$PATH}"
    create: yes

###############################################################################

- name: clone minc-toolkit-extras
  git:
    repo: https://github.com/CoBrALab/minc-toolkit-extras.git
    dest: /opt/quarantine/minc-toolkit-extras

- name: enable minc-toolkit-extras
  lineinfile:
    path: /etc/profile.d/99minc-toolkit-extras.sh
    line: "export PATH=/opt/quarantine/minc-toolkit-extras${PATH:+:$PATH}"
    create: yes
