---
- name: Install Docker APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install singularity build dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - build-essential
    - libssl-dev
    - uuid-dev
    - libgpgme11-dev
    - squashfs-tools
    - libseccomp-dev
    - wget
    - pkg-config
    - git
    - cryptsetup
    - golang-go

- name: create singularity directories
  file:
    path: /opt/quarantine/singularity/src
    state: directory

- name: Download singularity
  unarchive:
    src: https://github.com/hpcng/singularity/releases/download/v3.5.3/singularity-3.5.3.tar.gz
    dest: /opt/quarantine/singularity/src
    creates: /opt/quarantine/singularity/src/singularity
    remote_src: yes

- name: configure and install singularity
  shell: ./mconfig --prefix=/opt/quarantine/singularity && make -j {{ ansible_processor_vcpus }} -C ./builddir && make -C ./builddir install
  args:
    chdir: /opt/quarantine/singularity/src/singularity
    creates: /opt/quarantine/singularity/bin/singularity

- name: add singularity to path
  lineinfile:
    path: /etc/profile.d/99singularity.sh
    line: "export PATH=/opt/quarantine/singularity/bin${PATH:+:$PATH}"
    create: yes


###############################################################################

- name: create CIVET path
  ansible.builtin.file:
    path: /opt/quarantine/CIVET/2.1.1
    state: directory

- name: Build CIVET container
  shell: /opt/quarantine/singularity/bin/singularity build /opt/quarantine/CIVET/2.1.1/civet-2.1.1.simg docker://mcin/civet:2.1.1
  args:
    creates: /opt/quarantine/CIVET/2.1.1/civet-2.1.1.simg

- name: CIVET singularity wrapper
  copy:
    src: files/CIVET_Processing_Pipeline
    dest: /opt/quarantine/CIVET/2.1.1/
    mode: u=rwx,g=rx,u=rx

- name: add CIVET to path
  lineinfile:
    path: /etc/profile.d/99civet.sh
    line: "export PATH=/opt/quarantine/CIVET/2.1.1${PATH:+:$PATH}"
    create: yes

###############################################################################

- name: create fMRIprep path
  ansible.builtin.file:
    path: /opt/quarantine/fMRIprep/
    state: directory

- name: Build fmriprep container
  shell: /opt/quarantine/singularity/bin/singularity build /opt/quarantine/fMRIprep/fmriprep-20.2.6.simg docker://nipreps/fmriprep:20.2.6
  args:
    creates: /opt/quarantine/fMRIprep/fmriprep-20.2.6.simg

- name: fMRIprep singularity wrapper
  copy:
    src: files/fmriprep
    dest: /opt/quarantine/fMRIprep/
    mode: u=rwx,g=rx,u=rx

- name: add fMRIprep to path
  lineinfile:
    path: /etc/profile.d/99fmriprep.sh
    line: "export PATH=/opt/quarantine/fMRIprep/${PATH:+:$PATH}"
    create: yes