- name: Install Docker APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install singularity build dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - build-essential
    - libssl-dev
    - uuid-dev
    - libgpgme11-dev
    - squashfs-tools
    - libseccomp-dev
    - wget
    - pkg-config
    - git
    - cryptsetup
    - golang-go

- name: create singularity directories
  file:
    path: /opt/quarantine/singularity/src
    state: directory

- name: Download singularity
  unarchive:
    src: https://github.com/hpcng/singularity/releases/download/v3.5.3/singularity-3.5.3.tar.gz
    dest: /opt/quarantine/singularity/src
    creates: /opt/quarantine/singularity/src/singularity
    remote_src: yes

- name: configure and install singularity
  shell: ./mconfig --prefix=/opt/quarantine/singularity && make -C ./builddir && make -C ./builddir install
  args:
    chdir: /opt/quarantine/singularity/src/singularity
    creates: /opt/quarantine/singularity/bin/singularity

- name: add singularity to path
  lineinfile:
    path: /etc/profile.d/99singularity.sh
    line: "export PATH=/opt/quarantine/singularity/bin${PATH:+:$PATH}"
    create: yes
