- name: install debs
  apt: deb={{ item }}
  with_items:
    - https://www.mendeley.com/repositories/ubuntu/stable/amd64/mendeleydesktop-latest
    - https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.5033-amd64.deb
    - https://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.9.17-20190313-Ubuntu_18.04-x86_64.deb
    - https://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.0.09-20170529-Ubuntu_18.04-x86_64.deb
    - http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/beast-library-1.1.0-20121212.deb
    - http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/bic-mni-models-0.1.1-20120421.deb
  ignore_errors: yes
