- name: Install minc-toolkit-v2 build deps
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - bc
    - bison
    - flex
    - libx11-dev
    - x11proto-core-dev
    - libxi6
    - libxi-dev
    - libxmu6
    - libxmu-dev
    - libxmu-headers
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libjpeg-dev
    - libssl-dev
    - zlib1g-dev
    - automake
    - cpanminus

- cpanm: name="Math::Matrix"

###############################################################################

- name: install minc-toolkit-v2
  apt: deb={{ item }}
  with_items:
    - https://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.9.17-20190313-Ubuntu_18.04-x86_64.deb
    - https://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.0.09-20170529-Ubuntu_18.04-x86_64.deb

- name: install minc-toolkit-v2 resources
  apt: deb={{ item }}
  with_items:
    - http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/beast-library-1.1.0-20121212.deb
    - http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/bic-mni-models-0.1.1-20120421.deb
  tags:
    - resources

- name: enable minc-toolkit
  lineinfile:
    path: /etc/profile.d/98minc-toolkit.sh
    line: ". /opt/minc/1.9.17/minc-toolkit-config.sh"
    create: yes

###############################################################################

- name: Install pyminc (python)
  pip:
    name: pyminc
    executable: /opt/quarantine/miniforge/bin/pip
  tags:
    - python

###############################################################################

- name: create minc-stuffs directories
  file:
    path: /opt/quarantine/minc-stuffs
    state: directory

- name: clone minc-stuffs
  git:
    repo: https://github.com/Mouse-Imaging-Centre/minc-stuffs.git
    dest: /opt/quarantine/minc-stuffs/src
    version: v0.1.25

- name: Install minc-stuffs (python)
  pip:
    name: /opt/quarantine/minc-stuffs/src
    executable: /opt/quarantine/miniforge/bin/pip
  tags:
    - python

- name: Install minc-stuffs (perl)
  shell: . /opt/minc/1.9.17/minc-toolkit-config.sh && ./autogen.sh && ./configure --prefix=/opt/minc/1.9.17 --with-minc2 --with-build-path=/opt/minc/1.9.17 && make && make install
  args:
    chdir: /opt/quarantine/minc-stuffs/src
    creates: /opt/quarantine/minc-stuffs/src/config.log
    executable: /bin/bash

###############################################################################

- name: create minc2-simple directories
  file:
    path: /opt/quarantine/minc2-simple/build
    state: directory

- name: clone minc2-simple
  git:
    repo: https://github.com/vfonov/minc2-simple.git
    dest: /opt/quarantine/minc2-simple/src
    version: v2.2.30

- name: Install minc2-simple (python)
  shell: /opt/quarantine/miniforge/bin/python setup.py build && /opt/quarantine/miniforge/bin/python setup.py install
  args:
    chdir: /opt/quarantine/minc2-simple/src/python
    creates: /opt/quarantine/miniforge/bin/xfmavg_scipy.py
  tags:
    - python

- name: Install minc2-simple (C)
  shell: . /opt/minc/1.9.17/minc-toolkit-config.sh && cmake -DCMAKE_INSTALL_PREFIX=/opt/minc/1.9.17 ../src && make && make install
  args:
    chdir: /opt/quarantine/minc2-simple/build
    creates: /opt/quarantine/minc2-simple/build/CMakeCache.txt
    executable: /bin/bash

###############################################################################

- name: Install pydpiper dependencies (python)
  shell: /opt/quarantine/miniforge/bin/conda install --yes configargparse pyro4 ordered-set networkx pandas
  tags:
    - python

- name: Install pydpiper (python)
  pip:
    name: https://github.com/Mouse-Imaging-Centre/pydpiper/archive/v2.0.14.tar.gz
    executable: /opt/quarantine/miniforge/bin/pip
  tags:
    - python
