- apt: upgrade=dist update_cache=yes

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: Install Common APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - ncdu
    - htop
    - iotop
    - xauth
    - landscape-common
    - tmux
    - screen
    - imagemagick
    - exfat-utils
    - ntfs-3g
    - dosfstools
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - dmraid
    - dmsetup
    - kpartx
    - cryptsetup
    - openssh-server
    - parallel
    - quota
    - nmap
    - lrzip
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi-core
    - kubuntu-restricted-addons
    - kubuntu-restricted-extras
    - ansible
    - apparmor-profiles-extra
    - apparmor-profiles
    - smartmontools
    - squashfs-tools
    - links2
    - aptitude
    - tree
    - unattended-upgrades
    - nvme-cli
    - libpng12-0
    # DSI-studio deps
    - libqt5charts5
    - libqt5opengl5

- name: Install Development APT Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    autoclean: yes
    autoremove: yes
  vars:
    packages:
    - vim
    - emacs
    - build-essential
    - source-highlight
    - cmake
    - cmake-curses-gui
    - kitware-archive-keyring
    - ninja-build
    - gcc
    - gfortran
    - default-jre
    - git
    - make

- name: Install x2go session
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    install_recommends: no
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - lxqt-core
      - openbox
      - x2goserver
      - x2goserver-xsession
      - x2golxdebindings

- name: Install workstation apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - partitionmanager
      - language-pack-en
      - language-pack-fr
      - wcanadian-huge
      - hunspell-en-ca
      - hunspell-en-med
      - feh
      - xfig
      - meshlab
      - google-chrome-stable
      - libreoffice
      - libreoffice-plasma
      - libreoffice-style-breeze
      - muon


- name: Install texlive
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  vars:
    packages:
      - texlive-base
      - texlive-bibtex-extra
      - texlive-binaries
      - texlive-extra-utils
      - texlive-font-utils
      - texlive-fonts-extra
      - texlive-fonts-extra-links
      - texlive-fonts-recommended
      - texlive-formats-extra
      - texlive-games
      - texlive-humanities
      - texlive-lang-english
      - texlive-lang-french
      - texlive-lang-greek
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-luatex
      - texlive-metapost
      - texlive-music
      - texlive-pictures
      - texlive-plain-generic
      - texlive-pstricks
      - texlive-publishers
      - texlive-science
      - texlive-xetex
      - texlive-bibtex-extra
      - texlive-formats-extra
      - texlive-games
      - texlive-humanities
      - texlive-music
      - texlive-publishers
      - texlive-science

- name: Cleanup
  shell: apt-get clean
  args:
    warn: false

- name: install miscellaneous debs
  apt: deb={{ item }}
  with_items:
    - https://www.mendeley.com/repositories/ubuntu/stable/amd64/mendeleydesktop-latest
    - https://atom.io/download/deb
    - https://go.microsoft.com/fwlink/?LinkID=760868
    - https://zoom.us/client/latest/zoom_amd64.deb
  ignore_errors: yes
