---
- name: download anaconda
  get_url:
    url: https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh
    dest: /tmp/Anaconda3-2021.05-Linux-x86_64.sh

- name: install anaconda
  shell: bash /tmp/Anaconda3-2021.05-Linux-x86_64.sh -b -p /opt/quarantine/anaconda
  args:
    creates: /opt/quarantine/anaconda

- name: install pycryptosat
  shell: /opt/quarantine/anaconda/bin/conda install pycryptosat -S --yes

- name: configure condarc
  copy:
    src: files/condarc
    dest: /opt/quarantine/anaconda/.condarc

- name: install mamba
  shell: /opt/quarantine/anaconda/bin/conda install mamba -S --yes

- name: Install conda packages
  shell: >
      /opt/quarantine/anaconda/bin/mamba install -S --yes
      nipype nilearn simpleitk itk dipy nibabel
      seaborn statsmodels pandas tqdm
      matplotlib xarray zarr dask pathos mrtrix3

- name: Install conda pip packages
  pip:
    name: "{{ packages }}"
    executable: /opt/quarantine/anaconda/bin/pip
  vars:
    packages:
      - qbatch
      - neurosynth
      - neuroquery
      - git+https://github.com/netneurolab/pypyls.git
      - cpac
      - tqdm

- name: activate conda for all terminals
  copy:
    src: files/99conda.sh
    dest: /etc/profile.d

###############################################################################

# - name: Create cbptools env
#   shell: >
#     /opt/quarantine/anaconda/bin/mamba create -n cbptools --yes
#     matplotlib==3.0.3 nibabel numpy pandas pyyaml scikit-learn
#     scipy seaborn scikit-image plotly
#   args:
#     creates: /opt/quarantine/anaconda/envs/cbptools

# - name: Install cbptools (python)
#   pip:
#     name: cbptools
#     executable: /opt/quarantine/anaconda/envs/cbptools/bin/pip

# ###############################################################################
#
# - name: Create allensdk env
#   shell: /opt/quarantine/anaconda/bin/conda create -n allensdk --yes python pip
#
# - name: Install allensdk
#   pip:
#     name: allensdk
#     executable: /opt/quarantine/anaconda/envs/allensdk/bin/pip
#
#
# ##############################################################################

- name: Cleanup conda
  shell: /opt/quarantine/anaconda/bin/mamba clean --all -f -y
