- name: Install science apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
  vars:
    packages:
      - mricron
      - datalad
      - connectome-workbench
      - afni
      - dcm2niix


- name: Create /opt/quarantine
  file:
    path: /opt/quarantine
    state: directory

- name: Install 3DSlicer
  unarchive:
    src: https://download.slicer.org/bitstream/1023242
    dest: /opt/quarantine
    creates: /opt/quarantine/Slicer-4.10.2-linux-amd64
    remote_src: yes

- name: Install itksnap
  unarchive:
    src: http://www.nitrc.org/frs/downloadlink.php/11441
    dest: /opt/quarantine
    creates: /opt/quarantine/itksnap-3.8.0-20190612-Linux-gcc64-qt4
    remote_src: yes

- name: Install mricrogl
  unarchive:
    src: https://github.com/neurolabusc/MRIcroGL/releases/download/v1.0.20181111/MRIcroGL_linux.zip
    dest: /opt/quarantine
    creates: /opt/quarantine/MRIcroGL
    remote_src: yes

- name: mrtrix3 clone
  git:
    repo: 'https://github.com/MRtrix3/mrtrix3.git'
    dest: /opt/quarantine/mrtrix3
    version: 3.0_RC3_latest

- name: mrtrix3 build
  shell: ARCH=native ./configure && ./build
  args:
    chdir: /opt/quarantine/mrtrix3
    creates: /opt/quarantine/mrtrix3/build.log

- name: install r
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 3600
  vars:
    packages: "{{ lookup('file', 'files/r-list').splitlines() }}"

- name: install freesurfer
  unarchive:
    src: https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz
    dest: /opt/quarantine
    creates: /opt/quarantine/freesurfer
    remote_src: yes
