- name: restart rpcbind
  service: name=rpcbind state=restarted

- name: restart ypbind
  service: name=ypbind state=restarted

- name: restart autofs
  service: name=autofs state=restarted

- name: restart cups
  service: name=cups state=restarted

- name: restart cups-browsed
  service: name=cups-browsed state=restarted

- name: restart smartmontools
  service: name=smartmontools state=restarted

- name: restart apcupsd
  service: name=apcupsd state=restarted

- name: restart ntpd
  service: name=openntpd state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart watchdog
  service: name=watchdog state=restarted

- name: regen grub
  shell: update-grub
